### ISSUE TITLE
Readme and contribution files improvement

### ISSUE THREAD

**Issue by yelynn1** [yelynn1/tictactoe#2]
Need someone to write proper readme and contribution files. thanks

**Comment by yash2189** [comment]
Hi can I work on this?

**Comment by yelynn1** [comment]
yes. you can work on this. We welcome any kind of contribution that helps the project better. Thanks

**Comment by yash2189** [comment]
@yelynn1 I'll start working on it thanks can you please assign me this issue?

**Comment by yelynn1** [comment]
> @yelynn1 I'll start working on it thanks can you please assign me this issue?

I assigned to you. Thanks.

**Comment by yash2189** [comment]
Please review my PR #9 I have created two files `CONTRIBUTING.md` and `CODE OF CONDUCT.md` and improved the `README.md` file.
