### ISSUE TITLE
Make computer more intelligent

### ISSUE THREAD

**Issue by yelynn1** [yelynn1/tictactoe#3]
Currently, computer player is choosing random empty slot. It will be better if the computer player can choose the better slot rather than random.

**Comment by Flamer17** [comment]
Hey, i can improve this
can u assign this to me

**Comment by yelynn1** [comment]
Sure. We welcome any kind of improvement.

**Comment by AyushDubey-maker** [comment]
Is this issue still open?

**Comment by nakanaori** [comment]
Is this issue still open?

**Comment by yelynn1** [comment]
We welcome any kind of improvement and thanks for your interest in this project.
