### ISSUE TITLE
option to turn off the sounds at the end of the game

### ISSUE THREAD

**Issue by tsitsivakonstantinamaria** [yelynn1/tictactoe#58]
A button that turns off the sounds at the end of the game would be very useful

**Comment by samuel-gerges** [comment]
Hello, I would like to contribute to this project. Is it ok if I take this issue ?

**Comment by tsitsivakonstantinamaria** [comment]
> @tsitsivakonstantinamaria @yelynn1

yes its okay, sorry for taking so long to answer
